# Generated by Django 5.2.12 on 2026-04-22 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
