# Generated by Django 5.2.12 on 2026-05-08 17:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('descricao', models.TextField()),
                ('concluido', models.BooleanField(default=False)),
                ('equipe', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='equipes', to='core.equipe')),
            ],
        ),
    ]
