# Generated by Django 5.2.12 on 2026-04-22 12:55

import django.db.models.deletion
from django.db import migrations, models

def migrate_uuid_cast(apps, schema_editor):
    # Esta função verifica se o banco de dados é PostgreSQL antes de rodar o SQL manual
    if schema_editor.connection.vendor == 'postgresql':
        with schema_editor.connection.cursor() as cursor:
            # Converte a coluna de bigint para uuid usando cast explícito no Postgres
            cursor.execute("ALTER TABLE core_aluno ALTER COLUMN imagem_perfil_id TYPE uuid USING (imagem_perfil_id::text::uuid);")
            cursor.execute("ALTER TABLE core_professor ALTER COLUMN imagem_perfil_id TYPE uuid USING (imagem_perfil_id::text::uuid);")

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('uploader', '0002_remove_image_id_alter_image_attachment_key'),
    ]

    operations = [
        # Executa a lógica de conversão apenas se necessário (Postgres)
        migrations.RunPython(migrate_uuid_cast, reverse_code=migrations.RunPython.noop),
        
        migrations.AlterField(
            model_name='aluno',
            name='imagem_perfil',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='+', 
                to='uploader.image'
            ),
        ),
        migrations.AlterField(
            model_name='professor',
            name='imagem_perfil',
            field=models.ForeignKey(
                blank=True, 
                null=True, 
                on_delete=django.db.models.deletion.SET_NULL, 
                related_name='+', 
                to='uploader.image'
            ),
        ),
    ]