# Generated by Django 5.2.12 on 2026-08-26 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='alunos',
            field=models.ManyToManyField(blank=True, null=True, related_name='equipes', to='core.aluno'),
        ),
    ]
