# Generated by Django 5.2.12 on 2026-04-22 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aluno_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='is_professor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='is_professor',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='username',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
