# Generated by Django 5.2.12 on 2026-04-22 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aluno_is_professor_professor_is_professor_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='is_professor',
            new_name='is_aluno',
        ),
    ]
