# Generated by Django 5.2.12 on 2026-09-16 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_descricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='views',
            field=models.IntegerField(default=0),
        ),
    ]
