# Generated by Django 5.2.12 on 2026-08-11 12:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_convite'),
    ]

    operations = [
        migrations.AddField(
            model_name='convite',
            name='convidante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convites_enviados', to='core.professor'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='aluno',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convites_recebidos_aluno', to='core.aluno'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='convites', to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='professor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='convites_recebidos_professor', to='core.professor'),
        ),
    ]
