# Generated by Django 5.2.12 on 2026-09-24 23:06

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_item_descricao'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='convite',
            name='convidante',
        ),
        migrations.RemoveField(
            model_name='convite',
            name='professor',
        ),
        migrations.AddField(
            model_name='convite',
            name='codigoConfirmacao',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='convite',
            name='codigoExpiracao',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convite',
            name='criacao',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convite',
            name='enviadosPor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='convites_enviados', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='convite',
            name='resposta',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='convite',
            name='tentativas',
            field=models.PositiveSmallIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='convite',
            name='aluno',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convite_recebido', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='convite',
            name='equipe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='convites', to='core.equipe'),
        ),
        migrations.AlterField(
            model_name='convite',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendente'), ('awaiting_confirmation', 'Aguardando confirmação'), ('accepted', 'Aceito'), ('declined', 'Recusado')], default='pending', max_length=30),
        ),
        migrations.AddConstraint(
            model_name='convite',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['pending', 'awaiting_confirmation'])), fields=('equipe', 'aluno'), name='conviteUnicoPorAluno'),
        ),
    ]
