# Generated by Django 5.2.12 on 2026-09-18 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_equipe_views'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='titulo',
            field=models.CharField(max_length=30),
        ),
    ]
