# Generated by Django 5.2.12 on 2026-04-23 21:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_estado_instituicao'),
    ]

    operations = [
        migrations.AlterField(
            model_name='professor',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.instituicao'),
        ),
    ]
