# Generated by Django 5.2.12 on 2026-08-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_post_postimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='posts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='posts_projetos', to='core.post'),
            preserve_default=False,
        ),
    ]
