# Generated by Django 5.2.12 on 2026-09-22 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_projeto_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='categoria',
            field=models.CharField(choices=[('SENSORES', 'Sensores'), ('ATUADORES', 'Atuadores e Motores'), ('MICROCONTROLADORES', 'Microcontroladores e Placas'), ('ELETRONICA', 'Componentes Eletrônicos'), ('ESTRUTURA', 'Peças Estruturais e Chassi'), ('ALIMENTACAO', 'Baterias e Alimentação'), ('FERRAMENTAS', 'Ferramentas e Equipamentos'), ('CABEAMENTO', 'Cabos e Conectores'), ('FIXACAO', 'Parafusos e Fixadores'), ('IMPRESSAO_3D', 'Filamentos e Peças 3D'), ('OUTROS', 'Outros')], default='OUTROS', max_length=30),
        ),
    ]
