# Generated by Django 5.2.12 on 2026-04-24 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_professor_instituicao'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='instituicao',
            name='sigla',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='descricao',
            field=models.TextField(blank=True, max_length=1000, null=True),
        ),
    ]
