# Generated by Django 5.2.3 on 2026-04-24 18:34

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_aluno_descricao_instituicao_sigla_and_more'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=50)),
                ('descricao', models.CharField(blank=True, max_length=1000, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('alunos', models.ManyToManyField(blank=True, related_name='alunos', to='core.aluno')),
                ('image_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image')),
                ('instituicao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instituiçao', to='core.instituicao')),
                ('professores', models.ManyToManyField(blank=True, related_name='professores', to='core.professor')),
            ],
            options={
                'verbose_name': 'equipe',
                'verbose_name_plural': 'equipes',
            },
        ),
    ]
