# Generated by Django 5.2.12 on 2026-03-31 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_aluno_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='aluno',
            name='email_verificado',
            field=models.BooleanField(default=False),
        ),
    ]
