# Generated by Django 5.2.12 on 2026-08-12 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_projeto_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projeto',
            name='posts',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts_projetos', to='core.post'),
        ),
    ]
