# Generated by Django 5.2.12 on 2026-08-12 13:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_projeto_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projeto',
            name='posts',
        ),
        migrations.AddField(
            model_name='post',
            name='projeto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='core.projeto'),
        ),
    ]
