# Generated by Django 5.2.3 on 2026-04-25 00:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_equipe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipe',
            name='alunos',
            field=models.ManyToManyField(blank=True, related_name='equipes', to='core.aluno'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='instituicao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='equipes', to='core.instituicao'),
        ),
        migrations.AlterField(
            model_name='equipe',
            name='professores',
            field=models.ManyToManyField(blank=True, related_name='equipes', to='core.professor'),
        ),
    ]
