# Generated by Django 5.2.12 on 2026-08-12 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_remove_projeto_posts_post_projeto'),
    ]

    operations = [
        migrations.AddField(
            model_name='projeto',
            name='descricao',
            field=models.TextField(default=0),
            preserve_default=False,
        ),
    ]
