# Generated by Django 5.2.12 on 2026-04-15 12:52

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_aluno_imagem_perfil'),
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('cpf', models.CharField(max_length=11, unique=True)),
                ('senha', models.CharField(max_length=400)),
                ('telefone', models.CharField(max_length=15)),
                ('data_nascimento', models.DateField()),
                ('instituicao', models.CharField(max_length=300)),
                ('ativo', models.BooleanField(default=True)),
                ('email_verificado', models.BooleanField(default=False)),
                ('imagem_perfil', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='uploader.image', to_field='attachment_key')),
            ],
            options={
                'verbose_name': 'professor',
                'verbose_name_plural': 'professores',
                'ordering': ['id'],
            },
        ),
    ]
