# Generated by Django 5.2.3 on 2026-04-29 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipe',
            name='categorias',
            field=models.ManyToManyField(blank=True, related_name='equipes', to='core.categoria'),
        ),
    ]
