# Generated by Django 5.2.12 on 2026-04-22 12:55

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('uploader', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='id',
        ),
        migrations.AlterField(
            model_name='image',
            name='attachment_key',
            field=models.UUIDField(default=uuid.uuid4, help_text='Used to attach the image to another object. Cannot be used to retrieve the image file.', primary_key=True, serialize=False, unique=True),
        ),
    ]
